/**
 * CurriculumView2 — Phase accordion for a single goal's curriculum.
 */

import { useState } from 'react';
import {
  ChevronDown, ChevronRight, CheckCircle2, Clock, Award, Lock,
} from 'lucide-react';
import type { LearningGoal, CurriculumPhase, AssessmentStatus } from '../../types/academy';

interface CurriculumView2Props {
  goal: LearningGoal;
  onOpenLesson: (lessonId: string) => void;
}

const ASSESSMENT_COLORS: Record<AssessmentStatus, string> = {
  locked: '#5A7A9A',
  available: '#D4AF37',
  in_progress: '#F97316',
  passed: '#39FF14',
  failed: '#F43F5E',
};

export function CurriculumView2({ goal, onOpenLesson }: CurriculumView2Props) {
  const [expandedPhase, setExpandedPhase] = useState<string | null>(
    goal.curriculum?.phases[goal.currentPhaseIndex]?.id ?? null
  );

  if (!goal.curriculum) {
    return (
      <div style={{ padding: 40, textAlign: 'center', color: '#5A7A9A' }}>
        No curriculum generated yet.
      </div>
    );
  }

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
      <h2 style={{ fontSize: 20, fontWeight: 700, color: '#fff', marginBottom: 4 }}>
        {goal.topic}
      </h2>
      <div style={{ fontSize: 12, color: '#8BA4BE', marginBottom: 8 }}>
        {goal.curriculum.totalLessons} lessons total
        &middot; ~{goal.curriculum.totalEstimatedHours}h estimated
        &middot; Generated by {goal.curriculum.generatedBy}
      </div>

      {goal.curriculum.phases.map((phase, phaseIdx) => {
        const isExpanded = expandedPhase === phase.id;
        const allLessons = phase.topics.flatMap(t => t.lessons);
        const completedCount = allLessons.filter(l => l.completedAt).length;
        const totalCount = allLessons.length;
        const percent = totalCount > 0 ? Math.round((completedCount / totalCount) * 100) : 0;
        const isCurrent = phaseIdx === goal.currentPhaseIndex;

        return (
          <div key={phase.id} style={{
            borderRadius: 12, overflow: 'hidden',
            border: `1px solid ${isCurrent ? 'rgba(0,212,255,0.2)' : 'rgba(255,255,255,0.06)'}`,
            background: 'rgba(255,255,255,0.02)',
          }}>
            {/* Phase Header */}
            <button
              onClick={() => setExpandedPhase(isExpanded ? null : phase.id)}
              style={{
                display: 'flex', alignItems: 'center', gap: 12, width: '100%',
                padding: '14px 16px', border: 'none', cursor: 'pointer',
                background: isCurrent ? 'rgba(0,212,255,0.04)' : 'transparent',
                textAlign: 'left',
              }}
            >
              <div style={{
                width: 28, height: 28, borderRadius: '50%',
                background: percent === 100 ? 'rgba(57,255,20,0.15)' : 'rgba(0,212,255,0.1)',
                display: 'flex', alignItems: 'center', justifyContent: 'center',
                fontSize: 13, fontWeight: 700,
                color: percent === 100 ? '#39FF14' : '#00D4FF',
                flexShrink: 0,
              }}>
                {percent === 100 ? <CheckCircle2 size={16} /> : phaseIdx + 1}
              </div>
              <div style={{ flex: 1 }}>
                <div style={{ fontSize: 15, fontWeight: 600, color: '#fff', marginBottom: 2 }}>
                  {phase.title}
                </div>
                <div style={{ fontSize: 12, color: '#8BA4BE' }}>
                  {phase.description}
                </div>
              </div>
              <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                <div style={{ textAlign: 'right' }}>
                  <div style={{ fontSize: 12, fontWeight: 600, color: '#00D4FF' }}>
                    {percent}%
                  </div>
                  <div style={{ fontSize: 11, color: '#5A7A9A' }}>
                    {completedCount}/{totalCount}
                  </div>
                </div>
                <span style={{ fontSize: 11, color: '#5A7A9A', whiteSpace: 'nowrap' }}>
                  ~{phase.estimatedWeeks}w
                </span>
                {isExpanded ? <ChevronDown size={16} color="#8BA4BE" /> : <ChevronRight size={16} color="#8BA4BE" />}
              </div>
            </button>

            {/* Lessons */}
            {isExpanded && (
              <div style={{ padding: '4px 12px 12px' }}>
                {phase.topics.map(topic => (
                  <div key={topic.id}>
                    {phase.topics.length > 1 && (
                      <div style={{
                        fontSize: 12, fontWeight: 600, color: '#8BA4BE',
                        padding: '8px 8px 4px', textTransform: 'uppercase',
                        letterSpacing: '0.5px',
                      }}>
                        {topic.title}
                      </div>
                    )}
                    {topic.lessons.map(lesson => {
                      const isDone = !!lesson.completedAt;
                      return (
                        <button
                          key={lesson.id}
                          onClick={() => onOpenLesson(lesson.id)}
                          style={{
                            display: 'flex', alignItems: 'center', gap: 8, width: '100%',
                            padding: '10px 10px', border: 'none', borderRadius: 8,
                            background: 'transparent', cursor: 'pointer', textAlign: 'left',
                          }}
                        >
                          {isDone ? (
                            <CheckCircle2 size={16} color="#39FF14" />
                          ) : (
                            <div style={{
                              width: 16, height: 16, borderRadius: '50%',
                              border: '2px solid rgba(255,255,255,0.15)',
                              flexShrink: 0,
                            }} />
                          )}
                          <span style={{
                            fontSize: 13, flex: 1,
                            color: isDone ? '#5A7A9A' : '#D0D0D0',
                            textDecoration: isDone ? 'line-through' : 'none',
                          }}>
                            {lesson.title}
                          </span>
                          <span style={{
                            fontSize: 11, color: '#5A7A9A',
                            display: 'flex', alignItems: 'center', gap: 3,
                          }}>
                            <Clock size={10} /> {lesson.estimatedMinutes}m
                          </span>
                        </button>
                      );
                    })}
                  </div>
                ))}

                {/* Assessment badge */}
                {phase.assessmentStatus !== 'locked' && (
                  <div style={{
                    display: 'flex', alignItems: 'center', gap: 8,
                    padding: '10px 12px', marginTop: 8,
                    background: `${ASSESSMENT_COLORS[phase.assessmentStatus]}08`,
                    border: `1px solid ${ASSESSMENT_COLORS[phase.assessmentStatus]}30`,
                    borderRadius: 8,
                  }}>
                    {phase.assessmentStatus === 'passed' ? (
                      <Award size={16} color={ASSESSMENT_COLORS[phase.assessmentStatus]} />
                    ) : (
                      <Lock size={16} color={ASSESSMENT_COLORS[phase.assessmentStatus]} />
                    )}
                    <span style={{
                      fontSize: 12, fontWeight: 600,
                      color: ASSESSMENT_COLORS[phase.assessmentStatus],
                    }}>
                      Phase Assessment
                      {phase.assessmentStatus === 'available' && ' — Ready'}
                      {phase.assessmentStatus === 'passed' && ' — Passed'}
                      {phase.assessmentStatus === 'failed' && ' — Try Again'}
                    </span>
                  </div>
                )}
              </div>
            )}
          </div>
        );
      })}
    </div>
  );
}
